apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nextcloud-local
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/diegofnunesbr/nextcloud.git
    targetRevision: main
    path: manifests
    directory:
      include: nextcloud-local.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: nextcloud
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
