apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nextcloud
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/diegofnunesbr/nextcloud.git
    targetRevision: main
    path: .
    directory:
      include: nextcloud.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: nextcloud

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
